# Generated by Django 5.0.4 on 2024-04-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("calories", models.CharField(max_length=255)),
                ("fats", models.CharField(max_length=255)),
                ("carbs", models.CharField(max_length=255)),
                ("proteins", models.CharField(max_length=255)),
                ("unsaturated_fats", models.CharField(max_length=255)),
                ("sugar", models.CharField(max_length=255)),
                ("salt", models.CharField(max_length=255)),
                ("portion", models.CharField(max_length=255)),
            ],
        ),
    ]
